# Generated by Django 6.0.4 on 2026-04-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_text',
            new_name='comment_text',
        ),
    ]
